require("./ltc_kline1m")
require("./eth_kline1m")
require("./ticker")
require("./lp/huopro/huopro_btc_kline1m")
require("./lp/okex/okex_btc_kline1m")
require("./lp/binance/binance_btc_kline1m")
require("./lp/bitfinex/bitfinex_btc_kline1m")
require("./httpserver/SimpleServer")